export const QUESTIONS = [

{ question: "Quelle est la capitale de la France ?", options: ["Paris","Rome","Madrid","Berlin"], answer: "Paris", reward: 100 },
{ question: "Quel est le plus grand océan ?", options: ["Atlantique","Indien","Arctique","Pacifique"], answer: "Pacifique", reward: 100 },
{ question: "Qui a peint la Joconde ?", options: ["Van Gogh","Picasso","Léonard de Vinci","Monet"], answer: "Léonard de Vinci", reward: 100 },
{ question: "Combien de continents existe-t-il ?", options: ["5","6","7","8"], answer: "7", reward: 100 },
{ question: "Quel est le plus grand désert ?", options: ["Sahara","Gobi","Arctique","Antarctique"], answer: "Antarctique", reward: 100 },

{ question: "Quelle planète est la plus proche du Soleil ?", options: ["Vénus","Mars","Mercure","Jupiter"], answer: "Mercure", reward: 100 },
{ question: "Quel pays a la plus grande population ?", options: ["USA","Inde","Chine","Brésil"], answer: "Inde", reward: 100 },
{ question: "Quelle est la langue la plus parlée au monde ?", options: ["Anglais","Espagnol","Mandarin","Français"], answer: "Mandarin", reward: 100 },
{ question: "Quel animal est le plus rapide ?", options: ["Lion","Guépard","Tigre","Cheval"], answer: "Guépard", reward: 100 },
{ question: "Quelle est la capitale du Japon ?", options: ["Pékin","Tokyo","Séoul","Bangkok"], answer: "Tokyo", reward: 100 },

{ question: "Qui a découvert l’Amérique ?", options: ["Colomb","Magellan","Vasco","Cook"], answer: "Colomb", reward: 100 },
{ question: "Quel est le plus long fleuve ?", options: ["Nil","Amazone","Yangtsé","Mississippi"], answer: "Nil", reward: 100 },
{ question: "Quel est le plus grand pays ?", options: ["USA","Chine","Canada","Russie"], answer: "Russie", reward: 100 },
{ question: "Combien de côtés a un hexagone ?", options: ["5","6","7","8"], answer: "6", reward: 100 },
{ question: "Quel est le métal le plus léger ?", options: ["Fer","Or","Lithium","Argent"], answer: "Lithium", reward: 100 },

{ question: "Qui est le fondateur de Microsoft ?", options: ["Steve Jobs","Bill Gates","Elon Musk","Zuckerberg"], answer: "Bill Gates", reward: 100 },
{ question: "Quel est le symbole chimique de l’eau ?", options: ["O2","H2O","CO2","HO"], answer: "H2O", reward: 100 },
{ question: "Quelle est la capitale de l’Italie ?", options: ["Milan","Naples","Rome","Venise"], answer: "Rome", reward: 100 },
{ question: "Quel est le plus grand mammifère ?", options: ["Éléphant","Baleine bleue","Girafe","Requin"], answer: "Baleine bleue", reward: 100 },
{ question: "Combien de jours dans une année ?", options: ["360","365","366","364"], answer: "365", reward: 100 },

{ question: "Quelle est la capitale de l’Espagne ?", options: ["Barcelone","Madrid","Valence","Séville"], answer: "Madrid", reward: 100 },
{ question: "Quel gaz respirons-nous ?", options: ["CO2","Oxygène","Azote","Hydrogène"], answer: "Oxygène", reward: 100 },
{ question: "Qui a inventé l’ampoule ?", options: ["Tesla","Edison","Newton","Galilée"], answer: "Edison", reward: 100 },
{ question: "Quel est le plus petit pays ?", options: ["Monaco","Malte","Vatican","Nauru"], answer: "Vatican", reward: 100 },
{ question: "Quel est l’animal le plus lent ?", options: ["Requin","Ours","Paresseux","Éléphant"], answer: "Paresseux", reward: 100 },

{ question: "Quel est le plus haut sommet ?", options: ["K2","Everest","Kilimandjaro","Mont Blanc"], answer: "Everest", reward: 100 },
{ question: "Combien de minutes dans une heure ?", options: ["50","60","70","80"], answer: "60", reward: 100 },
{ question: "Quelle est la monnaie des USA ?", options: ["Euro","Dollar","Livre","Yen"], answer: "Dollar", reward: 100 },
{ question: "Quel est le plus grand lac ?", options: ["Victoria","Supérieur","Baïkal","Tchad"], answer: "Supérieur", reward: 100 },
{ question: "Qui a écrit Harry Potter ?", options: ["Tolkien","Rowling","King","Hugo"], answer: "Rowling", reward: 100 },

{ question: "Quel est le plus rapide du monde animal ?", options: ["Aigle","Guépard","Faucon","Lion"], answer: "Faucon", reward: 100 },
{ question: "Quel est le plus grand organe humain ?", options: ["Cœur","Peau","Foie","Poumon"], answer: "Peau", reward: 100 },
{ question: "Combien de planètes ?", options: ["7","8","9","10"], answer: "8", reward: 100 },
{ question: "Quelle est la capitale du Canada ?", options: ["Toronto","Ottawa","Montréal","Vancouver"], answer: "Ottawa", reward: 100 },
{ question: "Quel est le symbole du fer ?", options: ["Fe","F","Ir","Fr"], answer: "Fe", reward: 100 },

{ question: "Quel sport utilise un ballon rond ?", options: ["Rugby","Foot","Basket","Tennis"], answer: "Foot", reward: 100 },
{ question: "Quelle couleur donne rouge + jaune ?", options: ["Vert","Orange","Bleu","Violet"], answer: "Orange", reward: 100 },
{ question: "Quel est le plus grand volcan ?", options: ["Etna","Mauna Loa","Vésuve","Fuji"], answer: "Mauna Loa", reward: 100 },
{ question: "Combien de secondes dans une minute ?", options: ["50","60","70","80"], answer: "60", reward: 100 },
{ question: "Quelle planète est rouge ?", options: ["Mars","Vénus","Terre","Jupiter"], answer: "Mars", reward: 100 },

{ question: "Quel pays a la Tour Eiffel ?", options: ["Italie","France","Espagne","Belgique"], answer: "France", reward: 100 },
{ question: "Quel est le plus grand animal terrestre ?", options: ["Girafe","Éléphant","Rhino","Hippopotame"], answer: "Éléphant", reward: 100 },
{ question: "Combien de lettres dans alphabet ?", options: ["24","25","26","27"], answer: "26", reward: 100 },
{ question: "Quel est le plus long os ?", options: ["Bras","Fémur","Crâne","Côte"], answer: "Fémur", reward: 100 },
{ question: "Qui a écrit Les Misérables ?", options: ["Zola","Hugo","Balzac","Camus"], answer: "Hugo", reward: 100 },

// 🔥 QUESTIONS DIFFICILES
{ question: "Quel philosophe a théorisé la volonté générale ?", options: ["Locke","Rousseau","Hobbes","Kant"], answer: "Rousseau", reward: 150 },
{ question: "Une proposition toujours vraie est appelée :", options: ["Hypothèse","Tautologie","Paradoxe","Syllogisme"], answer: "Tautologie", reward: 150 },
{ question: "Qui a proposé E = mc² ?", options: ["Newton","Einstein","Tesla","Galilée"], answer: "Einstein", reward: 150 },
{ question: "Quel est le carré de 12 ?", options: ["124","144","132","154"], answer: "144", reward: 150 },
{ question: "Dans une démocratie, qui a théorisé la séparation des pouvoirs ?", options: ["Voltaire","Montesquieu","Rousseau","Hegel"], answer: "Montesquieu", reward: 150 },
{ question: "Quel est le rôle principal de la monnaie ?", options: ["Décorer","Faciliter échanges","Contrôler","Créer richesse"], answer: "Faciliter échanges", reward: 150 },
{ question: "Quel écrivain a écrit 1984 ?", options: ["Orwell","Kafka","Camus","Hugo"], answer: "Orwell", reward: 150 },
{ question: "Quel est le plus petit nombre premier ?", options: ["0","1","2","3"], answer: "2", reward: 150 },
{ question: "Quelle est la dérivée de x² ?", options: ["x","2x","x²","2"], answer: "2x", reward: 150 },
{ question: "Une comparaison sans outil est :", options: ["Métaphore","Hyperbole","Anaphore","Litote"], answer: "Métaphore", reward: 150 },
{ question: "Quel philosophe est associé au concept du 'surhomme' ?", options: ["Nietzsche","Kant","Socrate","Descartes"], answer: "Nietzsche", reward: 150 },
{ question: "Quel est le résultat de 9² ?", options: ["72","81","99","90"], answer: "81", reward: 120 },
{ question: "Quel pays est le plus grand d’Afrique ?", options: ["Nigeria","Algérie","Égypte","Congo"], answer: "Algérie", reward: 130 },
{ question: "Quel gaz est responsable de l'effet de serre principal ?", options: ["Oxygène","Azote","CO2","Hydrogène"], answer: "CO2", reward: 140 },
{ question: "Qui a formulé les lois de la gravitation ?", options: ["Einstein","Newton","Galilée","Kepler"], answer: "Newton", reward: 120 },

{ question: "Quelle est la capitale de la Turquie ?", options: ["Istanbul","Ankara","Izmir","Bursa"], answer: "Ankara", reward: 110 },
{ question: "Quel est le symbole chimique du calcium ?", options: ["Ca","Cl","C","Cm"], answer: "Ca", reward: 120 },
{ question: "Combien font 7³ ?", options: ["343","240","147","321"], answer: "343", reward: 150 },
{ question: "Quel océan est le plus profond ?", options: ["Atlantique","Indien","Pacifique","Arctique"], answer: "Pacifique", reward: 120 },
{ question: "Quel est le plus grand producteur de pétrole ?", options: ["USA","Arabie Saoudite","Russie","Iran"], answer: "USA", reward: 150 },

{ question: "Quel est le synonyme de 'épistémologie' ?", options: ["Science","Connaissance","Étude de la connaissance","Logique"], answer: "Étude de la connaissance", reward: 180 },
{ question: "Quel écrivain a écrit 'Le Procès' ?", options: ["Kafka","Camus","Zola","Hugo"], answer: "Kafka", reward: 140 },
{ question: "Quel est le nombre de côtés d’un dodécagone ?", options: ["10","12","14","16"], answer: "12", reward: 140 },
{ question: "Quel est le rôle du foie ?", options: ["Respirer","Filtrer le sang","Pomper","Digérer"], answer: "Filtrer le sang", reward: 120 },
{ question: "Quel est le plus grand océan après le Pacifique ?", options: ["Atlantique","Indien","Arctique","Antarctique"], answer: "Atlantique", reward: 120 },

{ question: "Quelle est la monnaie du Japon ?", options: ["Won","Yuan","Yen","Ringgit"], answer: "Yen", reward: 100 },
{ question: "Quel est le carré de 15 ?", options: ["215","225","235","205"], answer: "225", reward: 130 },
{ question: "Quel pays a pour capitale Oslo ?", options: ["Suède","Norvège","Danemark","Finlande"], answer: "Norvège", reward: 110 },
{ question: "Quel est le symbole du cuivre ?", options: ["Cu","Co","C","Cr"], answer: "Cu", reward: 120 },
{ question: "Quel est le plus grand désert chaud ?", options: ["Gobi","Sahara","Atacama","Kalahari"], answer: "Sahara", reward: 110 },

{ question: "Qui a écrit 'La Nausée' ?", options: ["Sartre","Camus","Nietzsche","Hegel"], answer: "Sartre", reward: 150 },
{ question: "Quelle est la racine carrée de 169 ?", options: ["11","12","13","14"], answer: "13", reward: 120 },
{ question: "Quel est le plus long fleuve d’Asie ?", options: ["Gange","Yangtsé","Mékong","Indus"], answer: "Yangtsé", reward: 130 },
{ question: "Quel est le plus grand pays d’Europe ?", options: ["France","Ukraine","Russie","Espagne"], answer: "Russie", reward: 120 },
{ question: "Quel est le rôle du cœur ?", options: ["Respirer","Pomper le sang","Filtrer","Digérer"], answer: "Pomper le sang", reward: 100 }
];