export const QUESTIONS = [
  { question: "En logique, comment s'appelle une conclusion tirée à partir de prémisses ?", options: ["Déduction", "Intuition", "Dissonance", "Hypothèse"], answer: "Déduction", reward: 100 },
  { question: "Quel philosophe est associé à la formule « Je pense, donc je suis » ?", options: ["Kant", "Descartes", "Spinoza", "Socrate"], answer: "Descartes", reward: 100 },
  { question: "Dans un raisonnement scientifique, que cherche-t-on principalement à éliminer ?", options: ["La précision", "La réfutation", "L'erreur", "L'illustration"], answer: "L'erreur", reward: 100 },
  { question: "Quelle figure de style consiste à répéter un mot au début de plusieurs phrases ?", options: ["Anaphore", "Métaphore", "Hyperbole", "Ellipse"], answer: "Anaphore", reward: 100 },
  { question: "Dans un graphique, que représente généralement l'axe vertical ?", options: ["Les catégories", "Les ordonnées", "Le temps", "Le titre"], answer: "Les ordonnées", reward: 100 },

  { question: "Quel nombre est premier ?", options: ["21", "27", "29", "39"], answer: "29", reward: 100 },
  { question: "Combien vaut 2 puissance 5 ?", options: ["10", "16", "32", "64"], answer: "32", reward: 100 },
  { question: "Quel est le prochain nombre dans la suite 2, 6, 12, 20, ... ?", options: ["28", "30", "32", "34"], answer: "30", reward: 100 },
  { question: "Un angle droit mesure :", options: ["45°", "60°", "90°", "180°"], answer: "90°", reward: 100 },
  { question: "Quelle est la racine carrée de 144 ?", options: ["10", "11", "12", "14"], answer: "12", reward: 100 },

  { question: "Quel auteur a écrit « Les Misérables » ?", options: ["Molière", "Hugo", "Zola", "Camus"], answer: "Hugo", reward: 100 },
  { question: "Quel écrivain est associé au roman « L'Étranger » ?", options: ["Sartre", "Camus", "Proust", "Balzac"], answer: "Camus", reward: 100 },
  { question: "Quel courant philosophique valorise l'expérience sensible comme source principale de connaissance ?", options: ["Rationalisme", "Empirisme", "Stoïcisme", "Dogmatisme"], answer: "Empirisme", reward: 100 },
  { question: "Quel philosophe a écrit « Le Contrat social » ?", options: ["Rousseau", "Montesquieu", "Voltaire", "Diderot"], answer: "Rousseau", reward: 100 },
  { question: "Dans « La Princesse de Clèves », l'autrice est :", options: ["Mme de La Fayette", "George Sand", "Colette", "Marguerite Duras"], answer: "Mme de La Fayette", reward: 100 },

  { question: "Quel poète est associé à « Les Fleurs du mal » ?", options: ["Rimbaud", "Baudelaire", "Verlaine", "Apollinaire"], answer: "Baudelaire", reward: 100 },
  { question: "Quel terme désigne un récit où le narrateur est dans l'histoire ?", options: ["Interne", "Externe", "Omniscient", "Collectif"], answer: "Interne", reward: 100 },
  { question: "Quel mot désigne une opposition d'idées dans un texte ?", options: ["Paradoxe", "Antithèse", "Pléonasme", "Euphémisme"], answer: "Antithèse", reward: 100 },
  { question: "Dans une dissertation, la problématique sert surtout à :", options: ["Raconter un exemple", "Poser la question centrale", "Faire la conclusion", "Définir un mot"], answer: "Poser la question centrale", reward: 100 },
  { question: "Quel dramaturge est l'auteur de « Tartuffe » ?", options: ["Molière", "Corneille", "Racine", "Beaumarchais"], answer: "Molière", reward: 100 },

  { question: "Quel événement marque le début de la Révolution française ?", options: ["Le sacre de Napoléon", "La prise de la Bastille", "La bataille de Waterloo", "Le traité de Versailles"], answer: "La prise de la Bastille", reward: 100 },
  { question: "Qui était le premier président des États-Unis ?", options: ["Lincoln", "Washington", "Jefferson", "Adams"], answer: "Washington", reward: 100 },
  { question: "Quelle civilisation a construit les pyramides de Gizeh ?", options: ["Romains", "Grecs", "Égyptiens", "Perses"], answer: "Égyptiens", reward: 100 },
  { question: "Quel empire était dirigé par Napoléon ?", options: ["Empire ottoman", "Empire romain", "Premier Empire français", "Empire byzantin"], answer: "Premier Empire français", reward: 100 },
  { question: "Quel document fondateur américain date de 1776 ?", options: ["La Constitution", "La Déclaration d'indépendance", "Le Bill of Rights", "Le traité de paix"], answer: "La Déclaration d'indépendance", reward: 100 },

  { question: "Quelle guerre s'est terminée en 1918 ?", options: ["Première Guerre mondiale", "Seconde Guerre mondiale", "Guerre de Corée", "Guerre froide"], answer: "Première Guerre mondiale", reward: 100 },
  { question: "Quel pays a été divisé en deux après 1945 et réunifié en 1990 ?", options: ["Italie", "Allemagne", "Autriche", "Pologne"], answer: "Allemagne", reward: 100 },
  { question: "Quelle institution adopte les lois en France ?", options: ["Le Conseil constitutionnel", "Le Parlement", "La Cour de cassation", "Le Sénat seul"], answer: "Le Parlement", reward: 100 },
  { question: "Quel droit est inscrit dans la Déclaration des droits de l'homme et du citoyen ?", options: ["Le droit à l'esclavage", "L'égalité devant la loi", "Le droit à la monarchie", "Le droit au secret bancaire"], answer: "L'égalité devant la loi", reward: 100 },
  { question: "Quel est le nom de la période de forte croissance économique après 1945 en Europe occidentale ?", options: ["Les Trente Glorieuses", "La Renaissance", "La Belle Époque", "Les Années folles"], answer: "Les Trente Glorieuses", reward: 100 },

  { question: "En économie, que mesure le PIB ?", options: ["Le nombre d'habitants", "La production de richesses", "Le niveau des salaires uniquement", "Le taux de chômage"], answer: "La production de richesses", reward: 100 },
  { question: "Quand la demande augmente et l'offre reste identique, le prix a tendance à :", options: ["Baisser", "Rester fixe", "Augmenter", "Disparaître"], answer: "Augmenter", reward: 100 },
  { question: "Quel mot décrit une situation de monopole sur un marché ?", options: ["Plusieurs vendeurs dominants", "Un seul vendeur dominant", "Aucun consommateur", "Un excès d'acheteurs"], answer: "Un seul vendeur dominant", reward: 100 },
  { question: "Une inflation élevée signifie :", options: ["Une baisse générale des prix", "Une hausse générale des prix", "Un arrêt des échanges", "Une hausse des salaires égale"], answer: "Une hausse générale des prix", reward: 100 },
  { question: "Quel acteur de l'économie paie des impôts et consomme ?", options: ["L'État seulement", "Le ménage", "La banque centrale", "La Bourse"], answer: "Le ménage", reward: 100 },

  { question: "Quel indicateur mesure le pourcentage de personnes sans emploi ?", options: ["Le PIB", "L'inflation", "Le chômage", "La croissance"], answer: "Le chômage", reward: 100 },
  { question: "Une entreprise qui vend en dessous de son coût de revient pratique :", options: ["La spéculation", "Le dumping", "La récession", "La diversification"], answer: "Le dumping", reward: 100 },
  { question: "Quel est le rôle principal de la Banque centrale ?", options: ["Écrire des romans", "Gérer la monnaie et la politique monétaire", "Fixer les équipes sportives", "Produire des biens"], answer: "Gérer la monnaie et la politique monétaire", reward: 100 },
  { question: "Dans une économie de marché, le prix dépend surtout de :", options: ["L'âge des vendeurs", "L'offre et la demande", "La météo uniquement", "La couleur du produit"], answer: "L'offre et la demande", reward: 100 },
  { question: "Quand une personne renonce à une décision pour une autre, on parle de :", options: ["Coût d'opportunité", "Dividend", "Inflation", "Subvention"], answer: "Coût d'opportunité", reward: 100 },

  { question: "Quel est le plus petit nombre premier pair ?", options: ["1", "2", "3", "4"], answer: "2", reward: 100 },
  { question: "Quel théorème relie les côtés d'un triangle rectangle ?", options: ["Thalès", "Pythagore", "Euclide", "Archimède"], answer: "Pythagore", reward: 100 },
  { question: "La somme des angles d'un triangle vaut :", options: ["90°", "120°", "180°", "360°"], answer: "180°", reward: 100 },
  { question: "Quel est le résultat de 15% de 200 ?", options: ["15", "20", "30", "40"], answer: "30", reward: 100 },
  { question: "Quelle fraction est équivalente à 1/2 ?", options: ["2/3", "3/6", "4/5", "5/8"], answer: "3/6", reward: 100 },

  { question: "Quel est le nombre romain pour 50 ?", options: ["L", "C", "X", "V"], answer: "L", reward: 100 },
  { question: "Quelle est la valeur de x dans l'équation x + 7 = 19 ?", options: ["10", "11", "12", "13"], answer: "12", reward: 100 },
  { question: "Quel est le périmètre d'un carré de côté 4 ?", options: ["8", "12", "16", "20"], answer: "16", reward: 100 },
  { question: "Combien y a-t-il de degrés dans un tour complet ?", options: ["90", "180", "270", "360"], answer: "360", reward: 100 },
  { question: "Quel est le résultat de 3² + 4² ?", options: ["5", "7", "25", "49"], answer: "25", reward: 100 },

  { question: "Quel gaz est majoritaire dans l'atmosphère terrestre ?", options: ["Oxygène", "Azote", "Dioxyde de carbone", "Hydrogène"], answer: "Azote", reward: 100 },
  { question: "Quel organe pompe le sang dans le corps humain ?", options: ["Foie", "Poumon", "Cœur", "Rein"], answer: "Cœur", reward: 100 },
  { question: "Quel est l'unité de mesure de la force ?", options: ["Watt", "Joule", "Newton", "Volt"], answer: "Newton", reward: 100 },
  { question: "Quelle planète est surnommée la planète rouge ?", options: ["Mars", "Vénus", "Saturne", "Mercure"], answer: "Mars", reward: 100 },
  { question: "Quel phénomène explique la chute d'une pomme au sol ?", options: ["Magnétisme", "Gravité", "Réflexion", "Fusion"], answer: "Gravité", reward: 100 },

  { question: "Quel acide est présent dans l'estomac humain ?", options: ["Acide sulfurique", "Acide chlorhydrique", "Acide citrique", "Acide nitrique"], answer: "Acide chlorhydrique", reward: 100 },
  { question: "Quelle est la molécule notée H2O ?", options: ["Hydrogène", "Oxygène", "Eau", "Sel"], answer: "Eau", reward: 100 },
  { question: "Quel est le plus grand os du corps humain ?", options: ["Humérus", "Fémur", "Tibia", "Radius"], answer: "Fémur", reward: 100 },
  { question: "Dans le système solaire, quelle planète a le plus grand nombre d'anneaux visibles ?", options: ["Mars", "Saturne", "Mercure", "Vénus"], answer: "Saturne", reward: 100 },
  { question: "Quel type de cellule transmet les messages nerveux ?", options: ["Globule rouge", "Neurone", "Ostéocyte", "Plaquette"], answer: "Neurone", reward: 100 },

  { question: "Quelle est la capitale du Canada ?", options: ["Toronto", "Ottawa", "Montréal", "Vancouver"], answer: "Ottawa", reward: 100 },
  { question: "Quelle ville est la capitale de l'Australie ?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: "Canberra", reward: 100 },
  { question: "Quel pays possède l'île de Madagascar ?", options: ["Madagascar", "Mozambique", "Suisse", "Indonésie"], answer: "Madagascar", reward: 100 },
  { question: "Quelle chaîne de montagnes sépare souvent l'Europe de l'Asie dans les cours de géographie scolaire ?", options: ["Andes", "Rocheuses", "Oural", "Alpes"], answer: "Oural", reward: 100 },
  { question: "Quel est le plus grand océan de la Terre ?", options: ["Atlantique", "Indien", "Pacifique", "Arctique"], answer: "Pacifique", reward: 100 },

  { question: "Quel pays a pour capitale Brasilia ?", options: ["Argentine", "Brésil", "Chili", "Pérou"], answer: "Brésil", reward: 100 },
  { question: "Quel est le plus long fleuve d'Afrique ?", options: ["Nil", "Amazone", "Zambèze", "Congo"], answer: "Nil", reward: 100 },
  { question: "Quel désert est le plus vaste du monde si l'on inclut les déserts polaires ?", options: ["Sahara", "Gobi", "Antarctique", "Kalahari"], answer: "Antarctique", reward: 100 },
  { question: "Quelle ville est surnommée la « ville lumière » ?", options: ["Madrid", "Paris", "Rome", "Londres"], answer: "Paris", reward: 100 },
  { question: "Quel détroit relie la mer Rouge à l'océan Indien via un passage stratégique ?", options: ["Gibraltar", "Ormuz", "Babel-Mandeb", "Béring"], answer: "Babel-Mandeb", reward: 100 },

  { question: "Quelle est la langue la plus parlée au monde en nombre de locuteurs natifs ?", options: ["Anglais", "Espagnol", "Mandarin", "Hindi"], answer: "Mandarin", reward: 100 },
  { question: "Quel mot désigne une phrase qui se contredit elle-même mais peut avoir un sens profond ?", options: ["Oxymore", "Antiphrase", "Euphémisme", "Pléonasme"], answer: "Oxymore", reward: 100 },
  { question: "En rhétorique, qu'est-ce qu'une question dont on n'attend pas de réponse ?", options: ["Question fermée", "Question rhétorique", "Question piège", "Question subsidiaire"], answer: "Question rhétorique", reward: 100 },
  { question: "Quel mot est l'antonyme de « rigueur » dans un contexte de méthode ?", options: ["Précision", "Laxisme", "Exactitude", "Cohérence"], answer: "Laxisme", reward: 100 },
  { question: "Quel est le pluriel correct de « alibi » ?", options: ["Alibis", "Alibies", "Alibis ou alibies", "Aucun pluriel"], answer: "Alibis", reward: 100 },

  { question: "Quel genre littéraire présente des personnages et une intrigue fictive ?", options: ["Poésie", "Roman", "Essai", "Discours"], answer: "Roman", reward: 100 },
  { question: "Quelle figure de style compare sans outil de comparaison explicite ?", options: ["Métaphore", "Comparaison", "Allégorie", "Métonymie"], answer: "Métaphore", reward: 100 },
  { question: "Dans un texte argumentatif, que cherche la thèse ?", options: ["Raconter", "Convaincre", "Décrire", "Inventer"], answer: "Convaincre", reward: 100 },
  { question: "Quel mot désigne la répétition inutile d'une même idée ?", options: ["Paradoxe", "Pléonasme", "Litote", "Ellipse"], answer: "Pléonasme", reward: 100 },
  { question: "Quel terme désigne un mot de sens opposé ?", options: ["Synonyme", "Antonyme", "Homonyme", "Paronyme"], answer: "Antonyme", reward: 100 },

  { question: "Quelle mer borde le nord de l'Afrique ?", options: ["Mer Noire", "Mer Méditerranée", "Mer Rouge", "Mer Caspienne"], answer: "Mer Méditerranée", reward: 100 },
  { question: "Quelle est la plus grande chaîne de montagnes terrestres ?", options: ["Andes", "Himalaya", "Atlas", "Alpes"], answer: "Himalaya", reward: 100 },
  { question: "Quel continent est traversé par la ligne de l'équateur et le méridien de Greenwich ?", options: ["Asie", "Afrique", "Europe", "Amérique"], answer: "Afrique", reward: 100 },
  { question: "Quelle capitale européenne est connue pour le Parlement et la Commission de l'UE ?", options: ["Rome", "Bruxelles", "Vienne", "Lisbonne"], answer: "Bruxelles", reward: 100 },
  { question: "Quel pays partage une frontière avec le Brésil et l'Argentine ?", options: ["Uruguay", "Chili", "Équateur", "Guyana"], answer: "Uruguay", reward: 100 },

  { question: "Quel archipel français est situé dans l'océan Indien ?", options: ["La Réunion", "Corse", "Bretagne", "Normandie"], answer: "La Réunion", reward: 100 },
  { question: "Quel océan se trouve entre l'Afrique et l'Australie ?", options: ["Pacifique", "Atlantique", "Indien", "Arctique"], answer: "Indien", reward: 100 },
  { question: "Quelle ville est la capitale du Maroc ?", options: ["Rabat", "Casablanca", "Fès", "Marrakech"], answer: "Rabat", reward: 100 },
  { question: "Quel pays est traversé par le Nil et possède Le Caire ?", options: ["Algérie", "Égypte", "Tunisie", "Liban"], answer: "Égypte", reward: 100 },
  { question: "Quel est le plus grand pays d'Amérique du Sud en superficie ?", options: ["Brésil", "Argentine", "Pérou", "Colombie"], answer: "Brésil", reward: 100 },

  { question: "Quel type de raisonnement part du cas général vers le cas particulier ?", options: ["Induction", "Déduction", "Abduction", "Analogisme"], answer: "Déduction", reward: 100 },
  { question: "Quel terme décrit l'art de bien parler ?", options: ["Rhétorique", "Syntaxe", "Prosodie", "Lexicologie"], answer: "Rhétorique", reward: 100 },
  { question: "Dans une analyse de texte, que signifie contextualiser ?", options: ["Changer le texte", "Le replacer dans son époque", "Le traduire", "Le résumer en une phrase"], answer: "Le replacer dans son époque", reward: 100 },
  { question: "Quel mot désigne une idée défendue par un auteur ?", options: ["Thèse", "Fable", "Métaphore", "Hypothèse"], answer: "Thèse", reward: 100 },
  { question: "Quel philosophe associe la morale au « devoir » ?", options: ["Kant", "Nietzsche", "Epicure", "Hobbes"], answer: "Kant", reward: 100 },

  { question: "Quel mouvement littéraire valorise la raison et les règles classiques ?", options: ["Romantisme", "Classicisme", "Surréalisme", "Symbolisme"], answer: "Classicisme", reward: 100 },
  { question: "Quel terme désigne l'argument qui soutient la thèse ?", options: ["Exemple", "Argument", "Illustration", "Témoin"], answer: "Argument", reward: 100 },
  { question: "Quel mot désigne une idée implicite non exprimée directement ?", options: ["Explicite", "Sous-entendu", "Définition", "Citation"], answer: "Sous-entendu", reward: 100 },
  { question: "Quelle discipline étudie les lois du raisonnement ?", options: ["Psychologie", "Logique", "Sociologie", "Économie"], answer: "Logique", reward: 100 },
  { question: "Quel est l'objectif principal d'une conclusion ?", options: ["Ouvrir le débat", "Fermer et synthétiser", "Changer de sujet", "Ajouter des preuves"], answer: "Fermer et synthétiser", reward: 100 },
];